-- [[Category:Collection modules]]
-- [[Category:Todo]]

return {
  { _id = 501, _name = "5inch Single Gun Mount", _type = 1, _icon = 1 },
  { _id = 502, _name = "5inch Twin Gun Mount", _type = 1, _icon = 1 },
  { _id = 503, _name = "3inch Single High-angle Gun Mount", _type = 1, _icon = 16 },
  { _id = 504, _name = "5inch Single Anti-Aircraft Gun Mount", _type = 2, _icon = 2 },
  { _id = 505, _name = "8inch Triple Gun Mount", _type = 2, _icon = 2 },
  { _id = 506, _name = "6inch Twin Rapid Fire Gun Mount", _type = 2, _icon = 2 },
  { _id = 507, _name = "14inch Twin Gun Mount", _type = 3, _icon = 3 },
  { _id = 508, _name = "16inch Twin Gun Mount", _type = 3, _icon = 3 },
  { _id = 509, _name = "16inch Triple Gun Mount", _type = 3, _icon = 3 },
  { _id = 510, _name = "5inch Single Anti-Aircraft Gun Mount (Secondary)", _type = 4, _icon = 16 },
  { _id = 511, _name = "6inch Single Gun Mount", _type = 4, _icon = 4 },
  { _id = 512, _name = "12.5inch Twin Secondary Gun Mount", _type = 4, _icon = 4 },
  { _id = 513, _name = "21inch Torpedo Early Model", _type = 5, _icon = 5 },
  { _id = 514, _name = "21inch Torpedo Late Model", _type = 5, _icon = 5 },
  { _id = 515, _name = "High-speed Abyssal Torpedo", _type = 5, _icon = 5 },
  { _id = 516, _name = "Abyssal Torpedo Bomber", _type = 8, _icon = 8 },
  { _id = 517, _name = "Abyssal Torpedo Bomber Mark.II", _type = 8, _icon = 8 },
  { _id = 518, _name = "Abyssal Torpedo Bomber Mark.III", _type = 8, _icon = 8 },
  { _id = 519, _name = "Abyssal Fighter", _type = 6, _icon = 6 },
  { _id = 520, _name = "Abyssal Fighter Mark.II", _type = 6, _icon = 6 },
  { _id = 521, _name = "Abyssal Fighter Mark.III", _type = 6, _icon = 6 },
  { _id = 522, _name = "Flying Fish Fighter", _type = 6, _icon = 6 },
  { _id = 523, _name = "Abyssal Dive Bomber", _type = 7, _icon = 7 },
  { _id = 524, _name = "Abyssal Dive Bomber Mark.II", _type = 7, _icon = 7 },
  { _id = 525, _name = "Abyssal Reconnaissance Plane", _type = 10, _icon = 10 },
  { _id = 526, _name = "Flying Fish Reconnaissance Plane", _type = 10, _icon = 10 },
  { _id = 527, _name = "Air Radar Mark.I", _type = 12, _icon = 11 },
  { _id = 528, _name = "Surface Radar Mark.I", _type = 12, _icon = 11 },
  { _id = 529, _name = "Surface Radar Mark.II", _type = 12, _icon = 11 },
  { _id = 530, _name = "Air Radar Mark.II", _type = 13, _icon = 11 },
  { _id = 531, _name = "Abyssal Surface Radar", _type = 13, _icon = 11 },
  { _id = 532, _name = "Abyssal Air Radar", _type = 13, _icon = 11 },
  { _id = 533, _name = "Improved Abyssal Turbine", _type = 17, _icon = 19 },
  { _id = 534, _name = "Enhanced Abyssal Boiler", _type = 17, _icon = 19 },
  { _id = 535, _name = "Anti-Air Dispersal Shell", _type = 18, _icon = 12 },
  { _id = 536, _name = "Deterioration Armor Piercing Shell", _type = 19, _icon = 13 },
  { _id = 537, _name = "12.7mm Machine Gun", _type = 21, _icon = 15 },
  { _id = 538, _name = "20mm Autocannon", _type = 21, _icon = 15 },
  { _id = 539, _name = "40mm Twin Autocannon Mount", _type = 21, _icon = 15 },
  { _id = 540, _name = "40mm Quadruple Autocannon Mount", _type = 21, _icon = 15 },
  { _id = 541, _name = "Abyssal Cuttlefish Torpedo", _type = 22, _icon = 5 },
  { _id = 542, _name = "Abyssal Depth Charge Projector", _type = 15, _icon = 17 },
  { _id = 543, _name = "Abyssal Sonar", _type = 14, _icon = 18 },
  { _id = 544, _name = "Abyssal Depth Charge Projector Mk.II", _type = 15, _icon = 17 },
  { _id = 545, _name = "Abyssal Sonar Mk.II", _type = 14, _icon = 18 },
  { _id = 546, _name = "Flying Fish Dive Bomber", _type = 7, _icon = 7 },
  { _id = 547, _name = "Abyssal Cat Fighter", _type = 6, _icon = 6 },
  { _id = 548, _name = "Abyssal Hell Dive Bomber", _type = 7, _icon = 7 },
  { _id = 549, _name = "Abyssal Revenge Torpedo Bomber", _type = 8, _icon = 8 },
  { _id = 550, _name = "5inch Twin Dual Purpose Gun Mount", _type = 1, _icon = 16 },
  { _id = 551, _name = "20inch Twin Gun Mount", _type = 3, _icon = 3 },
  { _id = 552, _name = "15inch Coastal Artillery", _type = 3, _icon = 3 },
  { _id = 553, _name = "4inch Twin Dual Purpose Gun Mount + CIC", _type = 1, _icon = 16 },
  { _id = 554, _name = "Abyssal Attack Seaplane", _type = 11, _icon = 10 },
  { _id = 555, _name = "Abyssal Attack Seaplane Kai", _type = 11, _icon = 10 },
  { _id = 556, _name = "Abyssal Cat Fighter Kai", _type = 6, _icon = 6 },
  { _id = 557, _name = "Abyssal Hell Dive Bomber Kai", _type = 7, _icon = 7 },
  { _id = 558, _name = "Abyssal Revenge Torpedo Bomber Kai", _type = 8, _icon = 8 },
  { _id = 559, _name = "Abyssal FCS + CIC", _type = 14, _icon = 18 },
  { _id = 560, _name = "Abyssal Searchlight", _type = 29, _icon = 24 },
  { _id = 561, _name = "Abyssal Liberation Land-based Dive Bomber", _type = 7, _icon = 7 },
  { _id = 562, _name = "Abyssal Liberation Land-based Dive Bomber Ace", _type = 7, _icon = 7 },
  { _id = 563, _name = "8inch Long Range Twin Gun Mount", _type = 2, _icon = 2 },
  { _id = 564, _name = "Abyssal Reconnaissance Observation Seaplane", _type = 10, _icon = 10 },
  { _id = 565, _name = "5inch Coastal Gun", _type = 1, _icon = 1 },
  { _id = 566, _name = "Abyssal Cat Fighter (Bombing)", _type = 7, _icon = 7 },
  { _id = 567, _name = "Coastal Radar", _type = 13, _icon = 11 },
  { _id = 568, _name = "16inch Triple Gun Mount (Strong)", _type = 3, _icon = 3 },
  { _id = 569, _name = "Abyssal Reconnaissance Flying Boat", _type = 10, _icon = 10 },
  { _id = 570, _name = "High-speed Abyssal Torpedo mod.2", _type = 22, _icon = 5 },
  { _id = 571, _name = "Abyssal Seaplane Tender Imp Aircraft", _type = 11, _icon = 10 },
  { _id = 572, _name = "Abyssal Bearcat Fighter", _type = 6, _icon = 6 },
  { _id = 573, _name = "Abyssal Submarine Floatplane", _type = 11, _icon = 10 },
  { _id = 574, _name = "Abyssal Patrolling Attack Hawk", _type = 8, _icon = 8 },
  { _id = 575, _name = "Abyssal Patrolling Attack Hawk Kai", _type = 8, _icon = 8 },
  { _id = 576, _name = "Abyssal 12inch Triple Gun Mount", _type = 3, _icon = 3 },
  { _id = 577, _name = "Abyssal 15inch Quadruple Gun Mount", _type = 3, _icon = 3 },
  { _id = 578, _name = "Abyssal 15inch Late Model Twin Gun Mount", _type = 3, _icon = 16 },
  { _id = 579, _name = "Abyssal 14inch Strait Double Gun Mount", _type = 3, _icon = 1 },
  { _id = 580, _name = "Abyssal Ambush Torpedo", _type = 22, _icon = 5 },
  { _id = 581, _name = "Abyssal Night Cat Fighter", _type = 6, _icon = 45 },
  { _id = 582, _name = "Abyssal Night Dive Bomber", _type = 7, _icon = 7 },
  { _id = 583, _name = "Abyssal Night Revenge Torpedo Bomber", _type = 8, _icon = 46 },
  { _id = 584, _name = "Abyssal 14inch Twin Gun Mount Kai", _type = 3, _icon = 3 },
  { _id = 585, _name = "Abyssal 16inch Triple Gun Mount Kai", _type = 3, _icon = 3 },
  { _id = 586, _name = "Abyssal Patrolling Attack Hawk Kai Ni", _type = 8, _icon = 8 },
  { _id = 587, _name = "Abyssal 16inch Triple Gun Mount Kai Ni", _type = 3, _icon = 3 },
  { _id = 588, _name = "Abyssal 5inch Twin Gun Mount Model C", _type = 1, _icon = 1 },
  { _id = 589, _name = "Abyssal 5.5inch Twin Gun Mount Kai", _type = 2, _icon = 2 },
  { _id = 590, _name = "Abyssal Target", _type = 22, _icon = 5},
  { _id = 591, _name = "Abyssal 5inch Single Gun Mount Mk.30", _type = 1, _icon = 16},
  { _id = 592, _name = "Abyssal 16inch Mk.VIII Twin Gun Mount Kai", _type = 3, _icon = 3 },
  { _id = 593, _name = "High-speed Abyssal Torpedo mod.3", _type = 5, _icon = 5 },
  { _id = 594, _name = "Abyssal Sky Fortress (Reconnaissance Model)", _type = 7, _icon = 7 },
  { _id = 595, _name = "Abyssal Sky Fortress Ace (Reconnaissance Model)", _type = 7, _icon = 7 },
  { _id = 596, _name = "Abyssal New Model 6inch Triple Rapid Fire Gun Mount", _type = 2, _icon = 2 },
  { _id = 597, _name = "Abyssal Sky Fortress (Heavy Bomber Model)", _type = 7, _icon = 7 },
  { _id = 598, _name = "Abyssal Sky Fortress Ace (Heavy Bomber Model)", _type = 7, _icon = 7 },
  { _id = 599, _name = "Abyssal 4.7inch Gun Mk.XII", _type = 1, _icon = 16 },
  { _id = 600, _name = "Abyssal 8inch Twin Rapid Fire Gun Mount", _type = 2, _icon = 2 },
  { _id = 601, _name = "Abyssal 8inch Triple Gun Mount Mk.9", _type = 2, _icon = 2 },
  { _id = 602, _name = "Abyssal 5inch Twin Dual-purpose Gun Mount (Concentrated Deployment)", _type = 1, _icon = 16 },
  { _id = 603, _name = "Abyssal Air Radar Mark.III + FCS", _type = 13, _icon = 11 },
  { _id = 604, _name = "Abyssal 5inch Twin Gun Mount Model A", _type = 1, _icon = 1 },
  { _id = 605, _name = "Abyssal Submarine Electronic Armament", _type = 51, _icon = 42 },
  { _id = 606, _name = "Abyssal 5inch Single High-angle Gun Mount Kai Ni", _type = 1, _icon = 16 },
  { _id = 607, _name = "Abyssal 5inch Twin High-angle Gun Mount Kai Ni", _type = 1, _icon = 16 },
  { _id = 608, _name = "Abyssal Night Operation Aviation Equipment", _type = 13, _icon = 11 },
  { _id = 609, _name = "Abyssal 16inch Triple Gun Mount Mk.6", _type = 2, _icon = 2 },
}