return {
  { _id = 1, _name = '12cm Single Gun Mount', _type = 1, _icon = 1 },
  { _id = 2, _name = '12.7cm Twin Gun Mount', _type = 1, _icon = 1 },
  { _id = 3, _name = '10cm Twin High-angle Gun Mount', _type = 1, _icon = 16 },
  { _id = 4, _name = '14cm Single Gun Mount', _type = 2, _icon = 2 },
  { _id = 5, _name = '15.5cm Triple Gun Mount', _type = 2, _icon = 2 },
  { _id = 6, _name = '20.3cm Twin Gun Mount', _type = 2, _icon = 2 },
  { _id = 7, _name = '35.6cm Twin Gun Mount', _type = 3, _icon = 3 },
  { _id = 8, _name = '41cm Twin Gun Mount', _type = 3, _icon = 3 },
  { _id = 9, _name = '46cm Triple Gun Mount', _type = 3, _icon = 3 },
  { _id = 10, _name = '12.7cm Twin High-angle Gun Mount', _type = 4, _icon = 16 },
  { _id = 11, _name = '15.2cm Single Gun Mount', _type = 4, _icon = 4 },
  { _id = 12, _name = '15.5cm Triple Secondary Gun Mount', _type = 4, _icon = 4 },
  { _id = 13, _name = '61cm Triple Torpedo Mount', _type = 5, _icon = 5 },
  { _id = 14, _name = '61cm Quadruple Torpedo Mount', _type = 5, _icon = 5 },
  { _id = 15, _name = '61cm Quadruple (Oxygen) Torpedo Mount', _type = 5, _icon = 5 },
  { _id = 16, _name = 'Type 97 Torpedo Bomber', _type = 8, _icon = 8 },
  { _id = 17, _name = 'Tenzan', _type = 8, _icon = 8 },
  { _id = 18, _name = 'Ryuusei', _type = 8, _icon = 8 },
  { _id = 19, _name = 'Type 96 Fighter', _type = 6, _icon = 6 },
  { _id = 20, _name = 'Type 0 Fighter Model 21', _type = 6, _icon = 6 },
  { _id = 21, _name = 'Type 0 Fighter Model 52', _type = 6, _icon = 6 },
  { _id = 22, _name = 'Prototype Reppuu Late Model', _type = 6, _icon = 6 },
  { _id = 23, _name = 'Type 99 Dive Bomber', _type = 7, _icon = 7 },
  { _id = 24, _name = 'Suisei', _type = 7, _icon = 7 },
  { _id = 25, _name = 'Type 0 Reconnaissance Seaplane', _type = 10, _icon = 10 },
  { _id = 26, _name = 'Zuiun', _type = 11, _icon = 10 },
  { _id = 27, _name = 'Type 13 Air Radar', _type = 12, _icon = 11 },
  { _id = 28, _name = 'Type 22 Surface Radar', _type = 12, _icon = 11 },
  { _id = 29, _name = 'Type 33 Surface Radar', _type = 12, _icon = 11 },
  { _id = 30, _name = 'Type 21 Air Radar', _type = 13, _icon = 11 },
  { _id = 31, _name = 'Type 32 Surface Radar', _type = 13, _icon = 11 },
  { _id = 32, _name = 'Type 42 Air Radar', _type = 13, _icon = 11 },
  { _id = 33, _name = 'Improved Kanhon Type Turbine', _type = 17, _icon = 19 },
  { _id = 34, _name = 'Enhanced Kanhon Type Boiler', _type = 17, _icon = 19 },
  { _id = 35, _name = 'Type 3 Shell', _type = 18, _icon = 12 },
  { _id = 36, _name = 'Type 91 Armor Piercing Shell', _type = 19, _icon = 13 },
  { _id = 37, _name = '7.7mm Machine Gun', _type = 21, _icon = 15 },
  { _id = 38, _name = '12.7mm Single Machine Gun Mount', _type = 21, _icon = 15 },
  { _id = 39, _name = '25mm Twin Autocannon Mount', _type = 21, _icon = 15 },
  { _id = 40, _name = '25mm Triple Autocannon Mount', _type = 21, _icon = 15 },
  { _id = 41, _name = 'Type A Kouhyouteki', _type = 22, _icon = 5 },
  { _id = 42, _name = 'Emergency Repair Personnel', _type = 23, _icon = 14 },
  { _id = 43, _name = 'Emergency Repair Goddess', _type = 23, _icon = 14 },
  { _id = 44, _name = 'Type 94 Depth Charge Projector', _type = 15, _icon = 17 },
  { _id = 45, _name = 'Type 3 Depth Charge Projector', _type = 15, _icon = 17 },
  { _id = 46, _name = 'Type 93 Passive Sonar', _type = 14, _icon = 18 },
  { _id = 47, _name = 'Type 3 Active Sonar', _type = 14, _icon = 18 },
  { _id = 48, _name = '12cm Single High-angle Gun Mount', _type = 1, _icon = 16 },
  { _id = 49, _name = '25mm Single Autocannon Mount', _type = 21, _icon = 15 },
  { _id = 50, _name = '20.3cm (No.3) Twin Gun Mount', _type = 2, _icon = 2 },
  { _id = 51, _name = '12cm 30-tube Rocket Launcher', _type = 21, _icon = 15 },
  { _id = 52, _name = 'Ryuusei Kai', _type = 8, _icon = 8 },
  { _id = 53, _name = 'Reppuu Model 11', _type = 6, _icon = 6 },
  { _id = 54, _name = 'Saiun', _type = 9, _icon = 9 },
  { _id = 55, _name = 'Shiden Kai 2', _type = 6, _icon = 6 },
  { _id = 56, _name = 'Shinden Kai', _type = 6, _icon = 6 },
  { _id = 57, _name = 'Suisei Model 12A', _type = 7, _icon = 7 },
  { _id = 58, _name = '61cm Quintuple (Oxygen) Torpedo Mount', _type = 5, _icon = 5 },
  { _id = 59, _name = 'Type 0 Observation Seaplane', _type = 10, _icon = 10 },
  { _id = 60, _name = 'Type 0 Fighter Model 62 (Fighter-bomber)', _type = 7, _icon = 7 },
  { _id = 61, _name = 'Type 2 Reconnaissance Aircraft', _type = 9, _icon = 9 },
  { _id = 62, _name = 'Prototype Seiran', _type = 11, _icon = 10 },
  { _id = 63, _name = '12.7cm Twin Gun Mount Model B Kai 2', _type = 1, _icon = 1 },
  { _id = 64, _name = 'Ju 87C Kai', _type = 7, _icon = 7 },
  { _id = 65, _name = '15.2cm Twin Gun Mount', _type = 2, _icon = 2 },
  { _id = 66, _name = '8cm High-angle Gun', _type = 4, _icon = 16 },
  { _id = 67, _name = '53cm Bow (Oxygen) Torpedo Mount', _type = 5, _icon = 5 },
  { _id = 68, _name = 'Daihatsu Landing Craft', _type = 24, _icon = 20 },
  { _id = 69, _name = 'Ka Type Observation Autogyro', _type = 25, _icon = 21 },
  { _id = 70, _name = 'Type 3 Command Liaison Aircraft (ASW)', _type = 26, _icon = 22 },
  { _id = 71, _name = '10cm Twin High-angle Gun Mount (Carriage)', _type = 4, _icon = 16 },
  { _id = 72, _name = 'Anti-torpedo Bulge (Medium)', _type = 27, _icon = 23 },
  { _id = 73, _name = 'Anti-torpedo Bulge (Large)', _type = 28, _icon = 23 },
  { _id = 74, _name = 'Searchlight', _type = 29, _icon = 24 },
  { _id = 75, _name = 'Drum Canister (Transport Use)', _type = 30, _icon = 25 },
  { _id = 76, _name = '38cm Twin Gun Mount', _type = 3, _icon = 3 },
  { _id = 77, _name = '15cm Twin Secondary Gun Mount', _type = 4, _icon = 4 },
  { _id = 78, _name = '12.7cm Single Gun Mount', _type = 1, _icon = 1 },
  { _id = 79, _name = 'Zuiun (634 Air Group)', _type = 11, _icon = 10 },
  { _id = 80, _name = 'Zuiun Model 12', _type = 11, _icon = 10 },
  { _id = 81, _name = 'Zuiun Model 12 (634 Air Group)', _type = 11, _icon = 10 },
  { _id = 82, _name = 'Type 97 Torpedo Bomber (931 Air Group)', _type = 8, _icon = 8 },
  { _id = 83, _name = 'Tenzan (931 Air Group)', _type = 8, _icon = 8 },
  { _id = 84, _name = '2cm Flakvierling 38', _type = 21, _icon = 15 },
  { _id = 85, _name = '3.7cm FlaK M42', _type = 21, _icon = 15 },
  { _id = 86, _name = 'Ship Repair Facility', _type = 31, _icon = 26 },
  { _id = 87, _name = 'New Model High Temperature High Pressure Boiler', _type = 17, _icon = 19 },
  { _id = 88, _name = 'Type 22 Surface Radar Kai 4', _type = 12, _icon = 11 },
  { _id = 89, _name = 'Type 21 Air Radar Kai', _type = 13, _icon = 11 },
  { _id = 90, _name = '20.3cm (No.2) Twin Gun Mount', _type = 2, _icon = 2 },
  { _id = 91, _name = '12.7cm Twin High-angle Gun Mount (Late Model)', _type = 1, _icon = 16 },
  { _id = 92, _name = 'Bi Type 40mm Twin Autocannon Mount', _type = 21, _icon = 15 },
  { _id = 93, _name = 'Type 97 Torpedo Bomber (Tomonaga Squadron)', _type = 8, _icon = 8 },
  { _id = 94, _name = 'Tenzan Model 12 (Tomonaga Squadron)', _type = 8, _icon = 8 },
  { _id = 95, _name = 'Submarine 53cm Bow Torpedo Mount (8 tubes)', _type = 32, _icon = 5 },
  { _id = 96, _name = 'Type 0 Fighter Model 21 (Skilled)', _type = 6, _icon = 6 },
  { _id = 97, _name = 'Type 99 Dive Bomber (Skilled)', _type = 7, _icon = 7 },
  { _id = 98, _name = 'Type 97 Torpedo Bomber (Skilled)', _type = 8, _icon = 8 },
  { _id = 99, _name = 'Type 99 Dive Bomber (Egusa Squadron)', _type = 7, _icon = 7 },
  { _id = 100, _name = 'Suisei (Egusa Squadron)', _type = 7, _icon = 7 },
  { _id = 101, _name = 'Star Shell', _type = 33, _icon = 27 },
  { _id = 102, _name = 'Type 98 Reconnaissance Seaplane (Night Recon)', _type = 10, _icon = 10 },
  { _id = 103, _name = 'Prototype 35.6cm Triple Gun Mount', _type = 3, _icon = 3 },
  { _id = 104, _name = '35.6cm Twin Gun Mount (Dazzle Camouflage)', _type = 3, _icon = 3 },
  { _id = 105, _name = 'Prototype 41cm Triple Gun Mount', _type = 3, _icon = 3 },
  { _id = 106, _name = 'Type 13 Air Radar Kai', _type = 12, _icon = 11 },
  { _id = 107, _name = 'Fleet Command Facility', _type = 34, _icon = 28 },
  { _id = 108, _name = 'Skilled Carrier-based Aircraft Maintenance Personnel', _type = 35, _icon = 29 },
  { _id = 109, _name = 'Zero Fighter Model 52C (601 Air Group)', _type = 6, _icon = 6 },
  { _id = 110, _name = 'Reppuu (601 Air Group)', _type = 6, _icon = 6 },
  { _id = 111, _name = 'Suisei (601 Air Group)', _type = 7, _icon = 7 },
  { _id = 112, _name = 'Tenzan (601 Air Group)', _type = 8, _icon = 8 },
  { _id = 113, _name = 'Ryuusei (601 Air Group)', _type = 8, _icon = 8 },
  { _id = 114, _name = '38cm Twin Gun Mount Kai', _type = 3, _icon = 3 },
  { _id = 115, _name = 'Ar196 Kai', _type = 10, _icon = 10 },
  { _id = 116, _name = 'Type 1 Armor Piercing Shell', _type = 19, _icon = 13 },
  { _id = 117, _name = 'Prototype 46cm Twin Gun Mount', _type = 3, _icon = 3 },
  { _id = 118, _name = 'Shiun', _type = 10, _icon = 10 },
  { _id = 119, _name = '14cm Twin Gun Mount', _type = 2, _icon = 2 },
  { _id = 120, _name = 'Type 91 Anti-Aircraft Fire Director', _type = 36, _icon = 30 },
  { _id = 121, _name = 'Type 94 Anti-Aircraft Fire Director', _type = 36, _icon = 30 },
  { _id = 122, _name = '10cm Twin High-angle Gun Mount + Anti-Aircraft Fire Director', _type = 1, _icon = 16 },
  { _id = 123, _name = 'SKC34 20.3cm Twin Gun Mount', _type = 2, _icon = 2 },
  { _id = 124, _name = 'FuMO25 Radar', _type = 13, _icon = 11 },
  { _id = 125, _name = '61cm Triple (Oxygen) Torpedo Mount', _type = 5, _icon = 5 },
  { _id = 126, _name = 'WG42 (Wurfgerät 42)', _type = 37, _icon = 31 },
  { _id = 127, _name = 'Prototype FaT Type 95 Oxygen Torpedo Kai', _type = 32, _icon = 5 },
  { _id = 128, _name = 'Prototype 51cm Twin Gun Mount', _type = 3, _icon = 3 },
  { _id = 129, _name = 'Skilled Lookouts', _type = 39, _icon = 32 },
  { _id = 130, _name = '12.7cm High-angle Gun + Anti-Aircraft Fire Director', _type = 4, _icon = 16 },
  { _id = 131, _name = '25mm Triple Autocannon Mount (Concentrated Deployment)', _type = 21, _icon = 15 },
  { _id = 132, _name = 'Type 0 Passive Sonar', _type = 40, _icon = 18 },
  { _id = 133, _name = '381mm/50 Triple Gun Mount', _type = 3, _icon = 3 },
  { _id = 134, _name = 'OTO 152mm Triple Rapid Fire Gun Mount', _type = 4, _icon = 4 },
  { _id = 135, _name = '90mm Single High-angle Gun Mount', _type = 4, _icon = 16 },
  { _id = 136, _name = 'Pugliese Underwater Protection Bulkhead', _type = 28, _icon = 23 },
  { _id = 137, _name = '381mm/50 Triple Gun Mount Kai', _type = 3, _icon = 3 },
  { _id = 138, _name = 'Type 2 Large Flying Boat', _type = 41, _icon = 33 },
  { _id = 139, _name = '15.2cm Twin Gun Mount Kai', _type = 2, _icon = 2 },
  { _id = 140, _name = 'Type 96 150cm Searchlight', _type = 42, _icon = 24 },
  { _id = 141, _name = 'Type 32 Surface Radar Kai', _type = 13, _icon = 11 },
  { _id = 142, _name = '15m Duplex Rangefinder + Type 21 Radar Kai Ni', _type = 13, _icon = 11 },
  { _id = 143, _name = 'Type 97 Torpedo Bomber (Murata Squadron)', _type = 8, _icon = 8 },
  { _id = 144, _name = 'Tenzan Model 12 (Murata Squadron)', _type = 8, _icon = 8 },
  { _id = 145, _name = 'Combat Ration', _type = 43, _icon = 34 },
  { _id = 146, _name = 'Underway Replenishment', _type = 44, _icon = 35 },
  { _id = 147, _name = '120mm/50 Twin Gun Mount', _type = 1, _icon = 1 },
  { _id = 148, _name = 'Prototype Nanzan', _type = 7, _icon = 7 },
  { _id = 149, _name = 'Type 4 Passive Sonar', _type = 14, _icon = 18 },
  { _id = 150, _name = 'Canned Saury', _type = 43, _icon = 34 },
  { _id = 151, _name = 'Prototype Keiun (Carrier-based Reconnaissance Model)', _type = 9, _icon = 9 },
  { _id = 152, _name = 'Type 0 Fighter Model 52 (Skilled)', _type = 6, _icon = 6 },
  { _id = 153, _name = 'Zero Fighter Model 52C (w/ Iwai Flight)', _type = 6, _icon = 6 },
  { _id = 154, _name = 'Zero Fighter Model 62 (Fighter-bomber / Iwai Squadron)', _type = 7, _icon = 7 },
  { _id = 155, _name = 'Zero Fighter Model 21 (w/ Iwamoto Flight)', _type = 6, _icon = 6 },
  { _id = 156, _name = 'Zero Fighter Model 52A (w/ Iwamoto Flight)', _type = 6, _icon = 6 },
  { _id = 157, _name = 'Type 0 Fighter Model 53 (Iwamoto Squadron)', _type = 6, _icon = 6 },
  { _id = 158, _name = 'Bf 109T Kai', _type = 6, _icon = 6 },
  { _id = 159, _name = 'Fw 190T Kai', _type = 6, _icon = 6 },
  { _id = 160, _name = '10.5cm Twin Gun Mount', _type = 4, _icon = 16 },
  { _id = 161, _name = '16inch Triple Gun Mount Mk.7', _type = 3, _icon = 3 },
  { _id = 162, _name = '203mm/53 Twin Gun Mount', _type = 2, _icon = 2 },
  { _id = 163, _name = 'Ro.43 Reconnaissance Seaplane', _type = 10, _icon = 10 },
  { _id = 164, _name = 'Ro.44 Seaplane Fighter', _type = 45, _icon = 43 },
  { _id = 165, _name = 'Type 2 Seaplane Fighter Kai', _type = 45, _icon = 43 },
  { _id = 166, _name = 'Daihatsu Landing Craft (Type 89 Medium Tank & Landing Force)', _type = 24, _icon = 20 },
  { _id = 167, _name = 'Special Type 2 Amphibious Tank', _type = 46, _icon = 36 },
  { _id = 168, _name = 'Type 96 Land-based Attack Aircraft', _type = 47, _icon = 37 },
  { _id = 169, _name = 'Type 1 Land-based Attack Aircraft', _type = 47, _icon = 37 },
  { _id = 170, _name = 'Type 1 Land-based Attack Aircraft (Nonaka Squadron)', _type = 47, _icon = 37 },
  { _id = 171, _name = 'OS2U', _type = 10, _icon = 10 },
  { _id = 172, _name = '5inch Twin Gun Mount Mk.28 mod.2', _type = 4, _icon = 16 },
  { _id = 173, _name = 'Bofors 40mm Quadruple Autocannon Mount', _type = 21, _icon = 15 },
  { _id = 174, _name = '53cm Twin Torpedo Mount', _type = 5, _icon = 5 },
  { _id = 175, _name = 'Raiden', _type = 48, _icon = 38 },
  { _id = 176, _name = 'Type 3 Fighter Hien', _type = 48, _icon = 44 },
  { _id = 177, _name = 'Type 3 Fighter Hien (244th Air Combat Group)', _type = 48, _icon = 44 },
  { _id = 178, _name = 'PBY-5A Catalina', _type = 41, _icon = 33 },
  { _id = 179, _name = 'Prototype 61cm Sextuple (Oxygen) Torpedo Mount', _type = 5, _icon = 5 },
  { _id = 180, _name = 'Type 1 Land-based Attack Aircraft Model 22A', _type = 47, _icon = 37 },
  { _id = 181, _name = 'Type 0 Fighter Model 32', _type = 6, _icon = 6 },
  { _id = 182, _name = 'Type 0 Fighter Model 32 (Skilled)', _type = 6, _icon = 6 },
  { _id = 183, _name = '16inch Triple Gun Mount Mk.7 + GFCS', _type = 3, _icon = 3 },
  { _id = 184, _name = 'Re.2001 OR Kai', _type = 6, _icon = 6 },
  { _id = 185, _name = 'Type 3 Fighter Hien Model 1D', _type = 48, _icon = 44 },
  { _id = 186, _name = 'Type 1 Land-based Attack Aircraft Model 34', _type = 47, _icon = 37 },
  { _id = 187, _name = 'Ginga', _type = 47, _icon = 37 },
  { _id = 188, _name = 'Re.2001 G Kai', _type = 8, _icon = 8 },
  { _id = 189, _name = 'Re.2005 Kai', _type = 6, _icon = 6 },
  { _id = 190, _name = '38.1cm Mk.I Twin Gun Mount', _type = 3, _icon = 3 },
  { _id = 191, _name = 'QF 2-pounder Octuple Pom-pom Gun Mount', _type = 21, _icon = 15 },
  { _id = 192, _name = '38.1cm Mk.I/N Twin Gun Mount Kai', _type = 3, _icon = 3 },
  { _id = 193, _name = 'Toku Daihatsu Landing Craft', _type = 24, _icon = 20 },
  { _id = 194, _name = 'Laté 298B', _type = 11, _icon = 10 },
  { _id = 195, _name = 'SBD', _type = 7, _icon = 7 },
  { _id = 196, _name = 'TBD', _type = 8, _icon = 8 },
  { _id = 197, _name = 'F4F-3', _type = 6, _icon = 6 },
  { _id = 198, _name = 'F4F-4', _type = 6, _icon = 6 },
  { _id = 199, _name = 'Jet Keiun Kai', _type = 57, _icon = 39 },
  { _id = 200, _name = 'Kikka Kai', _type = 57, _icon = 40 },
  { _id = 201, _name = 'Shiden Model 11', _type = 48, _icon = 38 },
  { _id = 202, _name = 'Shiden Model 21 Shiden Kai', _type = 48, _icon = 38 },
  { _id = 203, _name = 'New Kanhon Design Anti-torpedo Bulge (Medium)', _type = 27, _icon = 23 },
  { _id = 204, _name = 'New Kanhon Design Anti-torpedo Bulge (Large)', _type = 28, _icon = 23 },
  { _id = 205, _name = 'F6F-3', _type = 6, _icon = 6 },
  { _id = 206, _name = 'F6F-5', _type = 6, _icon = 6 },
  { _id = 207, _name = 'Zuiun (631 Air Group)', _type = 11, _icon = 10 },
  { _id = 208, _name = 'Seiran (631 Air Group)', _type = 11, _icon = 10 },
  { _id = 209, _name = 'Saiun (Disassembled for Transport)', _type = 50, _icon = 41 },
  { _id = 210, _name = 'Submarine Radar & Waterproof Telescope', _type = 51, _icon = 42 },
  { _id = 211, _name = 'Submarine Radar & Passive Radiolocator (E27)', _type = 51, _icon = 42 },
  { _id = 212, _name = 'Saiun (Eastern Caroline Air Group)', _type = 9, _icon = 9 },
  { _id = 213, _name = 'Late Model Bow Torpedo Mount (6 tubes)', _type = 32, _icon = 5 },
  { _id = 214, _name = 'Skilled Sonar Personnel + Late Model Bow Torpedo Mount (6 tubes)', _type = 32, _icon = 5 },
  { _id = 215, _name = 'Ro.44 Seaplane Fighter bis', _type = 45, _icon = 43 },
  { _id = 216, _name = 'Type 2 Seaplane Fighter Kai (Skilled)', _type = 45, _icon = 43 },
  { _id = 217, _name = 'Kyoufuu Kai', _type = 45, _icon = 43 },
  { _id = 218, _name = 'Type 4 Fighter Hayate', _type = 48, _icon = 44 },
  { _id = 219, _name = 'Type 0 Fighter Model 63 (Fighter-bomber)', _type = 7, _icon = 7 },
  { _id = 220, _name = '8cm High-angle Gun Kai + Additional Machine Guns', _type = 4, _icon = 16 },
  { _id = 221, _name = 'Type 1 Fighter Hayabusa Model II', _type = 48, _icon = 44 },
  { _id = 222, _name = 'Type 1 Fighter Hayabusa Model III A', _type = 48, _icon = 44 },
  { _id = 223, _name = 'Type 1 Fighter Hayabusa Model III A (54th Squadron)', _type = 48, _icon = 44 },
  { _id = 224, _name = 'Bomb-carrying Type 1 Fighter Hayabusa Model III Kai (65th Squadron)', _type = 47, _icon = 44 },
  { _id = 225, _name = 'Type 1 Fighter Hayabusa Model II (64th Squadron)', _type = 48, _icon = 44 },
  { _id = 226, _name = 'Type 95 Depth Charge', _type = 15, _icon = 17 },
  { _id = 227, _name = 'Type 2 Depth Charge', _type = 15, _icon = 17 },
  { _id = 228, _name = 'Type 96 Fighter Kai', _type = 6, _icon = 6 },
  { _id = 229, _name = '12.7cm Single High-angle Gun Mount (Late Model)', _type = 1, _icon = 16 },
  { _id = 230, _name = 'Toku Daihatsu Landing Craft + 11th Tank Regiment', _type = 24, _icon = 20 },
  { _id = 231, _name = '30.5cm Triple Gun Mount', _type = 3, _icon = 3 },
  { _id = 232, _name = '30.5cm Triple Gun Mount Kai', _type = 3, _icon = 3 },
  { _id = 233, _name = 'F4U-1D', _type = 7, _icon = 7 },
  { _id = 234, _name = '15.5cm Triple Secondary Gun Mount Kai', _type = 4, _icon = 4 },
  { _id = 235, _name = '15.5cm Triple Gun Mount Kai', _type = 2, _icon = 2 },
  { _id = 236, _name = '41cm Triple Gun Mount Kai', _type = 3, _icon = 3 },
  { _id = 237, _name = 'Zuiun (634 Air Group/Skilled)', _type = 11, _icon = 10 },
  { _id = 238, _name = 'Type 0 Reconnaissance Seaplane Model 11B', _type = 10, _icon = 10 },
  { _id = 239, _name = 'Type 0 Reconnaissance Seaplane Model 11B (Skilled)', _type = 10, _icon = 10 },
  { _id = 240, _name = 'Type 22 Surface Radar Kai 4 (Calibrated Late Model)', _type = 12, _icon = 11 },
  { _id = 241, _name = 'Combat Ration (Special Onigiri)', _type = 43, _icon = 34 },
  { _id = 242, _name = 'Swordfish', _type = 8, _icon = 8 },
  { _id = 243, _name = 'Swordfish Mk.II (Skilled)', _type = 8, _icon = 8 },
  { _id = 244, _name = 'Swordfish Mk.III (Skilled)', _type = 8, _icon = 8 },
  { _id = 245, _name = '38cm Quadruple Gun Mount', _type = 3, _icon = 3 },
  { _id = 246, _name = '38cm Quadruple Gun Mount Kai', _type = 3, _icon = 3 },
  { _id = 247, _name = '15.2cm Triple Gun Mount', _type = 4, _icon = 4 },
  { _id = 248, _name = 'Skua', _type = 7, _icon = 7 },
  { _id = 249, _name = 'Fulmar', _type = 6, _icon = 6 },
  { _id = 250, _name = 'Spitfire Mk.I', _type = 48, _icon = 44 },
  { _id = 251, _name = 'Spitfire Mk.V', _type = 48, _icon = 44 },
  { _id = 252, _name = 'Seafire Mk.III Kai', _type = 6, _icon = 6 },
  { _id = 253, _name = 'Spitfire Mk.IX (Skilled)', _type = 48, _icon = 44 },
  { _id = 254, _name = 'F6F-3N', _type = 6, _icon = 45 },
  { _id = 255, _name = 'F6F-5N', _type = 6, _icon = 45 },
  { _id = 256, _name = 'TBF', _type = 8, _icon = 8 },
  { _id = 257, _name = 'TBM-3D', _type = 8, _icon = 46 },
  { _id = 258, _name = 'Night Operation Aviation Personnel', _type = 35, _icon = 29 },
  { _id = 259, _name = 'Night Operation Aviation Personnel + Skilled Deckhands', _type = 35, _icon = 29 },
  { _id = 260, _name = 'Type124 ASDIC', _type = 14, _icon = 18 },
  { _id = 261, _name = 'Type144/147 ASDIC', _type = 14, _icon = 18 },
  { _id = 262, _name = 'HF/DF + Type144/147 ASDIC', _type = 14, _icon = 18 },
  { _id = 263, _name = 'Shiden Kai (343 Air Group) 301st Fighter Squadron', _type = 48, _icon = 38 },
  { _id = 266, _name = '12.7cm Twin Gun Mount Model C Kai 2', _type = 1, _icon = 1 },
  { _id = 267, _name = '12.7cm Twin Gun Mount Model D Kai 2', _type = 1, _icon = 1 },
  { _id = 268, _name = 'Arctic Camouflage (+ Arctic Equipment)', _type = 27, _icon = 23 },
  { _id = 269, _name = 'Prototype Toukai', _type = 47, _icon = 47 },
  { _id = 270, _name = 'Toukai (901 Air Group)', _type = 47, _icon = 47 },
  { _id = 271, _name = 'Shiden Kai 4', _type = 6, _icon = 6 },
  { _id = 272, _name = 'Striking Force Fleet Command Facility', _type = 34, _icon = 28 },
  { _id = 273, _name = 'Saiun (4th Recon Squad)', _type = 9, _icon = 9 },
  { _id = 274, _name = '12cm 30-tube Rocket Launcher Kai Ni', _type = 21, _icon = 15 },
  { _id = 275, _name = '10cm Twin High-angle Gun Mount Kai + Additional Machine Guns', _type = 4, _icon = 16 },
  { _id = 276, _name = '46cm Triple Gun Mount Kai', _type = 3, _icon = 3 },
  { _id = 277, _name = 'FM-2', _type = 7, _icon = 7 },
  { _id = 278, _name = 'SK Radar', _type = 13, _icon = 11 },
  { _id = 279, _name = 'SK + SG Radar', _type = 13, _icon = 11 },
  { _id = 280, _name = 'QF 4.7inch Gun Mk.XII Kai', _type = 1, _icon = 1 },
  { _id = 281, _name = '51cm Twin Gun Mount', _type = 3, _icon = 3 },
  { _id = 282, _name = '130mm B-13 Twin Gun Mount', _type = 1, _icon = 1 },
  { _id = 283, _name = '533mm Triple Torpedo Mount', _type = 5, _icon = 5 },
  { _id = 284, _name = '5inch Single Gun Mount Mk.30', _type = 1, _icon = 16 },
  { _id = 285, _name = '61cm Triple (Oxygen) Torpedo Mount Late Model', _type = 5, _icon = 5 },
  { _id = 286, _name = '61cm Quadruple (Oxygen) Torpedo Mount Late Model', _type = 5, _icon = 5 },
  { _id = 287, _name = 'Type 3 Depth Charge Projector (Concentrated Deployment)', _type = 15, _icon = 17 },
  { _id = 288, _name = 'Prototype 15cm 9-tube ASW Rocket Launcher', _type = 15, _icon = 17 },
  { _id = 289, _name = '35.6cm Triple Gun Mount Kai (Dazzle Camouflage)', _type = 3, _icon = 3 },
  { _id = 290, _name = '41cm Triple Gun Mount Kai Ni', _type = 3, _icon = 3 },
  { _id = 291, _name = 'Suisei Model 22 (634 Air Group)', _type = 7, _icon = 7 },
  { _id = 292, _name = 'Suisei Model 22 (634 Air Group/Skilled)', _type = 7, _icon = 7 },
  { _id = 293, _name = '12cm Single Gun Mount Kai 2', _type = 1, _icon = 1 },
  { _id = 294, _name = '12.7cm Twin Gun Mount Model A Kai 2', _type = 1, _icon = 1 },
  { _id = 295, _name = '12.7cm Twin Gun Mount Model A Kai 3 (Wartime Modification) + Anti-Aircraft Fire Director', _type = 1, _icon = 16 },
  { _id = 296, _name = '12.7cm Twin Gun Mount Model B Kai 4 (Wartime Modification) + Anti-Aircraft Fire Director', _type = 1, _icon = 16 },
  { _id = 297, _name = '12.7cm Twin Gun Mount Model A', _type = 1, _icon = 1 },
  { _id = 298, _name = '16inch Mk.I Triple Gun Mount', _type = 3, _icon = 3 },
  { _id = 299, _name = '16inch Mk.I Triple Gun Mount + AFCT Kai', _type = 3, _icon = 3 },
  { _id = 300, _name = '16inch Mk.I Triple Gun Mount Kai + FCR Type 284', _type = 3, _icon = 3 },
  { _id = 301, _name = '20-tube 7inch UP Rocket Launchers', _type = 21, _icon = 15 },
  { _id = 302, _name = 'Type 97 Torpedo Bomber (931 Air Group/Skilled)', _type = 8, _icon = 8 },
  { _id = 303, _name = 'Bofors 15.2cm Twin Gun Mount Model 1930', _type = 2, _icon = 2 },
  { _id = 304, _name = 'S9 Osprey', _type = 10, _icon = 10 },
  { _id = 305, _name = 'Ju 87C Kai Ni (w/ KMX)', _type = 7, _icon = 7 },
  { _id = 306, _name = 'Ju 87C Kai Ni (w/ KMX/Skilled)', _type = 7, _icon = 7 },
  { _id = 307, _name = 'GFCS Mk.37', _type = 12, _icon = 11 },
  { _id = 308, _name = '5inch Single Gun Mount Mk.30 Kai + GFCS Mk.37', _type = 1, _icon = 16 },
  { _id = 309, _name = 'Type C Kouhyouteki', _type = 22, _icon = 5 },
  { _id = 310, _name = '14cm Twin Gun Mount Kai', _type = 2, _icon = 2 },
  { _id = 311, _name = 'Type 2 Land-based Reconnaissance Aircraft', _type = 49, _icon = 9 },
  { _id = 312, _name = 'Type 2 Land-based Reconnaissance Aircraft (Skilled)', _type = 49, _icon = 9 },
  { _id = 313, _name = '5inch Single Gun Mount Mk.30 Kai', _type = 1, _icon = 16 },
  { _id = 314, _name = '533mm Quintuple Torpedo Mount (Initial Model)', _type = 5, _icon = 5 },
  { _id = 315, _name = 'SG Radar (Initial Model)', _type = 12, _icon = 11 },
  { _id = 316, _name = 'Re.2001 CB Kai', _type = 7, _icon = 7 },
  { _id = 317, _name = 'Type 3 Shell Kai', _type = 18, _icon = 12 },
  { _id = 318, _name = '41cm Twin Gun Mount Kai Ni', _type = 3, _icon = 3 },
  { _id = 319, _name = 'Suisei Model 12 (634 Air Group w/ Type 3 Cluster Bombs)', _type = 7, _icon = 7 },
  { _id = 320, _name = 'Suisei Model 12 (w/ Type 31 Photoelectric Fuze Bombs)', _type = 7, _icon = 7 },
  { _id = 322, _name = 'Zuiun Kai Ni (634 Air Group)', _type = 11, _icon = 10 },
  { _id = 323, _name = 'Zuiun Kai Ni (634 Air Group/Skilled)', _type = 11, _icon = 10 },
  { _id = 324, _name = 'O Type Observation Autogyro Kai', _type = 25, _icon = 21 },
  { _id = 325, _name = 'O Type Observation Autogyro Kai Ni', _type = 25, _icon = 21 },
  { _id = 326, _name = 'S-51J', _type = 25, _icon = 21 },
  { _id = 327, _name = 'S-51J Kai', _type = 25, _icon = 21 },
  { _id = 328, _name = '35.6cm Twin Gun Mount Kai', _type = 3, _icon = 3 },
  { _id = 329, _name = '35.6cm Twin Gun Mount Kai Ni', _type = 3, _icon = 3 },
  { _id = 330, _name = '16inch Mk.I Twin Gun Mount', _type = 3, _icon = 3 },
  { _id = 331, _name = '16inch Mk.V Twin Gun Mount', _type = 3, _icon = 3 },
  { _id = 332, _name = '16inch Mk.VIII Twin Gun Mount Kai', _type = 3, _icon = 3 },
  { _id = 333, _name = 'Reppuu Kai', _type = 48, _icon = 38 },
  { _id = 334, _name = 'Reppuu Kai (352 Air Group/Skilled)', _type = 48, _icon = 38 },
  { _id = 335, _name = 'Reppuu Kai (Prototype Carrier-based Model)', _type = 6, _icon = 6 },
  { _id = 336, _name = 'Reppuu Kai Ni', _type = 6, _icon = 6 },
  { _id = 337, _name = 'Reppuu Kai Ni (CarDiv 1/Skilled)', _type = 6, _icon = 6 },
  { _id = 338, _name = 'Reppuu Kai Ni Model E', _type = 6, _icon = 45 },
  { _id = 339, _name = 'Reppuu Kai Ni Model E (CarDiv 1/Skilled)', _type = 6, _icon = 45 },
  { _id = 340, _name = '152mm/55 Triple Rapid Fire Gun Mount', _type = 2, _icon = 2 },
  { _id = 341, _name = '152mm/55 Triple Rapid Fire Gun Mount Kai', _type = 2, _icon = 2 },
  { _id = 342, _name = 'Ryuusei Kai (CarDiv 1)', _type = 8, _icon = 8 },
  { _id = 343, _name = 'Ryuusei Kai (CarDiv 1/Skilled)', _type = 8, _icon = 8 },
  { _id = 344, _name = 'Prototype Type 97 Torpedo Bomber Kai No. 3 Model E (w/ Type 6 Airborne Radar Kai)', _type = 8, _icon = 46 },
  { _id = 345, _name = 'Prototype Type 97 Torpedo Bomber Kai (Skilled) No. 3 Model E (w/ Type 6 Airborne Radar Kai)', _type = 8, _icon = 46 },
  { _id = 346, _name = 'Type 2 12cm Mortar Kai', _type = 15, _icon = 17 },
  { _id = 347, _name = 'Type 2 12cm Mortar Kai (Concentrated Deployment)', _type = 15, _icon = 17 },
  { _id = 348, _name = 'Shipborne Model Type 4 20cm Anti-ground Rocket Launcher', _type = 37, _icon = 31 },
  { _id = 349, _name = 'Type 4 20cm Anti-ground Rocket Launcher (Concentrated Deployment)', _type = 37, _icon = 31 },
  { _id = 350, _name = 'Me 163B', _type = 48, _icon = 38 },
  { _id = 351, _name = 'Prototype Shuusui', _type = 48, _icon = 38 },
  { _id = 352, _name = 'Shuusui', _type = 48, _icon = 38 },
  { _id = 353, _name = 'Fw 190 A-5 Kai (Skilled)', _type = 6, _icon = 6 },
  { _id = 354, _name = 'Fw 190 D-9', _type = 48, _icon = 38 },
  { _id = 355, _name = 'M4A1 DD', _type = 24, _icon = 20 },
  { _id = 356, _name = '8inch Triple Gun Mount Mk.9', _type = 2, _icon = 2 },
  { _id = 357, _name = '8inch Triple Gun Mount Mk.9 mod.2', _type = 2, _icon = 2 },
  { _id = 358, _name = '5inch Single High-angle Gun Mount Battery', _type = 4, _icon = 16 },
  { _id = 359, _name = '6inch Twin Rapid Fire Gun Mount Mk.XXI', _type = 2, _icon = 2 },
  { _id = 360, _name = 'Bofors 15cm Twin Rapid Fire Gun Mount Mk.9 Model 1938', _type = 2, _icon = 2 },
  { _id = 361, _name = 'Bofors 15cm Twin Rapid Fire Gun Mount Mk.9 Kai + Single Rapid Fire Gun Mount Mk.10 Kai Model 1938', _type = 2, _icon = 2 },
  { _id = 362, _name = '5inch Twin Dual-purpose Gun Mount (Concentrated Deployment)', _type = 2, _icon = 16 },
  { _id = 363, _name = 'GFCS Mk.37 + 5inch Twin Dual-purpose Gun Mount (Concentrated Deployment)', _type = 2, _icon = 16 },
  { _id = 364, _name = 'Type D Kouhyouteki Kai (Kouryuu Kai)', _type = 22, _icon = 5 },
  { _id = 365, _name = 'Type 1 Armor Piercing Shell Kai', _type = 19, _icon = 13 },
  { _id = 366, _name = '12.7cm Twin Gun Mount Model D Kai 3', _type = 1, _icon = 1 },
  { _id = 367, _name = 'Swordfish (Seaplane Model)', _type = 11, _icon = 10 },
  { _id = 368, _name = 'Swordfish Mk.III Kai (Seaplane Model)', _type = 11, _icon = 10 },
  { _id = 369, _name = 'Swordfish Mk.III Kai (Seaplane Model/Skilled)', _type = 11, _icon = 10 },
  { _id = 370, _name = 'Swordfish Mk.II Kai (Reconnaissance Seaplane Model)', _type = 10, _icon = 10 },
  { _id = 371, _name = 'Fairey Seafox Kai', _type = 10, _icon = 10 },
  { _id = 372, _name = 'Tenzan Model 12A', _type = 8, _icon = 8 },
  { _id = 373, _name = 'Tenzan Model 12A Kai (w/ Type 6 Airborne Radar Kai)', _type = 8, _icon = 46 },
  { _id = 374, _name = 'Tenzan Model 12A Kai (Skilled w/ Type 6 Airborne Radar Kai)', _type = 8, _icon = 46 },
  { _id = 375, _name = 'XF5U', _type = 6, _icon = 6 },
  { _id = 376, _name = '533mm Quintuple Torpedo Mount (Late Model)', _type = 5, _icon = 5 },
  { _id = 377, _name = 'RUR-4A Weapon Alpha Kai', _type = 15, _icon = 17 },
  { _id = 378, _name = 'Lightweight ASW Torpedo (Initial Test Model)', _type = 15, _icon = 17 },
  { _id = 379, _name = '12.7cm Single High-angle Gun Mount Kai 2', _type = 1, _icon = 16 },
  { _id = 380, _name = '12.7cm Twin High-angle Gun Mount Kai 2', _type = 1, _icon = 16 },
  { _id = 381, _name = '16inch Triple Gun Mount Mk.6', _type = 3, _icon = 3 },
  { _id = 382, _name = '12cm Single High-angle Gun Mount Model E', _type = 1, _icon = 16 },
  { _id = 383, _name = 'Late Model 53cm Bow Torpedo Mount (8 tubes)', _type = 32, _icon = 5 },
  { _id = 384, _name = 'Late Model Submarine Radar & Passive Radiolocator', _type = 51, _icon = 42 },
  { _id = 385, _name = '16inch Triple Gun Mount Mk.6 mod.2', _type = 3, _icon = 3 },
  { _id = 386, _name = '6inch Triple Rapid Fire Gun Mount Mk.16', _type = 2, _icon = 2 },
  { _id = 387, _name = '6inch Triple Rapid Fire Gun Mount Mk.16 mod.2', _type = 2, _icon = 2 },
  { _id = 388, _name = 'Ginga (Egusa Squadron)', _type = 47, _icon = 37 },
  { _id = 389, _name = 'TBM-3W+3S', _type = 8, _icon = 46 },
  { _id = 390, _name = '16inch Triple Gun Mount Mk.6 + GFCS', _type = 3, _icon = 3 },
  { _id = 391, _name = 'Type 99 Dive Bomber Model 22', _type = 7, _icon = 7 },
  { _id = 392, _name = 'Type 99 Dive Bomber Model 22 (Skilled)', _type = 7, _icon = 7 },
  { _id = 393, _name = '120mm/50 Twin Gun Mount mod.1936', _type = 1, _icon = 1 },
  { _id = 394, _name = '120mm/50 Twin Gun Mount Kai A.mod.1937', _type = 1, _icon = 1 },
  { _id = 395, _name = 'Shinzan', _type = 53, _icon = 49 },
  { _id = 396, _name = 'Shinzan Kai', _type = 53, _icon = 49 },
  { _id = 397, _name = 'Locally Modified 12.7cm Twin High-angle Gun Mount', _type = 1, _icon = 16 },
  { _id = 398, _name = 'Locally Modified 10cm Twin High-angle Gun Mount', _type = 1, _icon = 16 },
  { _id = 399, _name = '6inch Mk.XXIII Triple Gun Mount', _type = 2, _icon = 2 },
  { _id = 400, _name = '533mm Triple Torpedo Mount (Model 53-39)', _type = 5, _icon = 5 },
  { _id = 401, _name = 'Do 17 Z-2', _type = 47, _icon = 37 },
  { _id = 402, _name = 'Arctic Gear & Deck Personnel', _type = 35, _icon = 29 },
  { _id = 403, _name = 'Type 4 Heavy Bomber Hiryuu', _type = 47, _icon = 37 },
  { _id = 404, _name = 'Type 4 Heavy Bomber Hiryuu (Skilled)', _type = 47, _icon = 37 },
  { _id = 405, _name = 'Do 217 E-5 + Hs293 Initial Model', _type = 47, _icon = 37 },
  { _id = 406, _name = 'Do 217 K-2 + Fritz-X', _type = 47, _icon = 37 },
  { _id = 407, _name = '15.2cm Twin Gun Mount Kai Ni', _type = 2, _icon = 2 },
  { _id = 408, _name = 'Soukoutei (Armored Boat Class)', _type = 24, _icon = 20 },
  { _id = 409, _name = 'Armed Daihatsu', _type = 24, _icon = 20 },
  { _id = 410, _name = 'Type 21 Air Radar Kai Ni', _type = 13, _icon = 11 },
  { _id = 411, _name = 'Type 42 Air Radar Kai Ni', _type = 13, _icon = 11 },
  { _id = 412, _name = 'Torpedo Squadron Skilled Lookouts', _type = 39, _icon = 32 },
  { _id = 414, _name = 'SOC Seagull', _type = 10, _icon = 10 },
}