return {
    [1] = { -- DE
        [1] = 1,
        [12] = 1,
        [14] = 1,
        [15] = 1,
        [21] = 1,
        [23] = 1,
        [36] = 1,
        [37] = 1,
        [39] = 1,
        [43] = 1,
    },
    [2] = { -- DD
        [1] = 1,
        [5] = 1,
        [12] = 1,
        [13] = {value = 2, note = "Kasumi Kai Ni B only", code = "Kasumi Kai Ni B"},
        [14] = 1,
        [15] = 1,
        [17] = 1,
        [20] = 1,
        [21] = 1,
        [23] = 1,
        [24] = {value = 2, note = "Arare Kai Ni, Arashio Kai Ni, Ariake Kai, Asashio Kai Ni D, Fumizuki Kai Ni, Kasumi Kai Ni, Kasumi Kai Ni B, Kawakaze Kai Ni, Kisaragi Kai Ni, Makigumo Kai Ni, Michishio Kai Ni, Mikazuki Kai, Murasame Kai Ni, Mutsuki Kai Ni, Ooshio Kai Ni, Satsuki Kai Ni, Umikaze Kai Ni and Verniy only", code = "Arare Kai Ni, Arashio Kai Ni, Ariake Kai, Asashio Kai Ni D, Fumizuki Kai Ni, Kasumi Kai Ni, Kasumi Kai Ni B, Kawakaze Kai Ni, Kisaragi Kai Ni, Makigumo Kai Ni, Michishio Kai Ni, Mikazuki Kai, Murasame Kai Ni, Mutsuki Kai Ni, Ooshio Kai Ni, Satsuki Kai Ni, Umikaze Kai Ni, Verniy"},
        [27] = {value = 2, note = "Asashimo Kai Ni, Fletcher Mk.II, Kagerou Kai Ni, Kazagumo Kai Ni, Kuroshio Kai Ni, Makigumo Kai Ni, Naganami Kai Ni, Okinami Kai Ni, Shiranui Kai Ni, Verniy, Yukikaze Kai Ni and Yuugumo Kai Ni only", code = "Asashimo Kai Ni, Fletcher Mk.II, Kagerou Kai Ni, Kazagumo Kai Ni, Kuroshio Kai Ni, Makigumo Kai Ni, Naganami Kai Ni, Okinami Kai Ni, Shiranui Kai Ni, Verniy, Yukikaze Kai Ni, Yuugumo Kai Ni"},
        [29] = 1,
        [30] = 1,
        [33] = 1,
        [34] = {value = 2, note = "Dan Yang, Fletcher Kai Mod.2, Fletcher Mk.II, Kasumi Kai Ni, Murasame Kai Ni, Naganami Kai Ni, Shiranui Kai Ni, Shiratsuyu Kai Ni, Umikaze Kai Ni, Yukikaze Kai Ni and Yuugumo Kai Ni only", code = "Dan Yang, Fletcher Kai Mod.2, Fletcher Mk.II, Kasumi Kai Ni, Murasame Kai Ni, Naganami Kai Ni, Shiranui Kai Ni, Shiratsuyu Kai Ni, Umikaze Kai Ni, Yukikaze Kai Ni, Yuugumo Kai Ni"},
        [36] = 1,
        [37] = 1,
        [39] = 1,
        [40] = {value = 2, note = "Fletcher Mk.II only", code = "Fletcher Mk.II"},
        [43] = 1,
        [46] = {value = 2, note = "Arare Kai Ni, Arashio Kai Ni, Asashimo Kai Ni, Asashio Kai Ni D, Fumizuki Kai Ni, Kasumi Kai Ni, Kasumi Kai Ni B, Kazagumo Kai Ni, Kuroshio Kai Ni, Michishio Kai Ni, Okinami Kai Ni, Ooshio Kai Ni, Satsuki Kai Ni, Shiratsuyu Kai Ni, Umikaze Kai Ni, Verniy and Yukikaze Kai Ni only", code = "Arare Kai Ni, Arashio Kai Ni, Asashimo Kai Ni, Asashio Kai Ni D, Fumizuki Kai Ni, Kasumi Kai Ni, Kasumi Kai Ni B, Kazagumo Kai Ni, Kuroshio Kai Ni, Michishio Kai Ni, Okinami Kai Ni, Ooshio Kai Ni, Satsuki Kai Ni, Shiratsuyu Kai Ni, Umikaze Kai Ni, Verniy, Yukikaze Kai Ni"},
    },
    [3] = { -- CL
        [1] = 1,
        [2] = 1,
        [4] = {value = 2, note = "Excluding Tatsuta Kai Ni, Tenryuu Kai Ni, Yuubari Kai Ni, Yuubari Kai Ni D and Yuubari Kai Ni Toku", code = "CL excluding Tatsuta Kai Ni, Tenryuu Kai Ni, Yuubari Kai Ni, Yuubari Kai Ni D, Yuubari Kai Ni Toku"},
        [5] = {value = 2, note = "Excluding Kuma Kai Ni D", code = "CL excluding Kuma Kai Ni D"},
        [10] = {value = 2, note = "Excluding Kuma Kai Ni D, Tatsuta Kai Ni, Tenryuu Kai Ni, Yuubari Kai Ni, Yuubari Kai Ni D and Yuubari Kai Ni Toku", code = "CL excluding Kuma Kai Ni D, Tatsuta Kai Ni, Tenryuu Kai Ni, Yuubari Kai Ni, Yuubari Kai Ni D, Yuubari Kai Ni Toku"},
        [11] = {value = 2, note = "Agano Kai, Gotland, Gotland Andra, Gotland Kai, Kuma Kai Ni, Noshiro Kai, Noshiro Kai Ni, Sakawa Kai, Tama Kai Ni, Yahagi Kai and Yura Kai Ni only", code = "Agano Kai, Gotland, Gotland Andra, Gotland Kai, Kuma Kai Ni, Noshiro Kai, Noshiro Kai Ni, Sakawa Kai, Tama Kai Ni, Yahagi Kai, Yura Kai Ni"},
        [12] = 1,
        [13] = {value = 2, note = "Excluding Gotland, Tatsuta Kai Ni, Tenryuu Kai Ni, Yuubari Kai Ni D and Yuubari Kai Ni Toku", code = "CL excluding Gotland, Tatsuta Kai Ni, Tenryuu Kai Ni, Yuubari Kai Ni D, Yuubari Kai Ni Toku"},
        [14] = 1,
        [15] = 1,
        [17] = 1,
        [20] = 1,
        [21] = 1,
        [22] = {value = 2, note = "Abukuma Kai Ni, Kuma Kai Ni D, Yura Kai Ni and Yuubari Kai Ni Toku only", code = "Abukuma Kai Ni, Kuma Kai Ni D, Yura Kai Ni, Yuubari Kai Ni Toku"},
        [23] = 1,
        [24] = {value = 2, note = "Abukuma Kai Ni, Gotland Andra, Kinu Kai Ni, Kuma Kai Ni D, Tama Kai Ni, Tatsuta Kai Ni, Yura Kai Ni and Yuubari Kai Ni Toku only", code = "Abukuma Kai Ni, Gotland Andra, Kinu Kai Ni, Kuma Kai Ni D, Tama Kai Ni, Tatsuta Kai Ni, Yura Kai Ni, Yuubari Kai Ni Toku"},
        [25] = {value = 2, note = "Gotland, Gotland Andra, Kuma Kai Ni, Noshiro Kai Ni, Tama Kai Ni, Tatsuta Kai Ni and Tenryuu Kai Ni only", code = "Gotland, Gotland Andra, Kuma Kai Ni, Noshiro Kai Ni, Tama Kai Ni, Tatsuta Kai Ni, Tenryuu Kai Ni"},
        [27] = {value = 2, note = "Agano Kai, Gotland Andra, Gotland Kai, Kiso Kai, Kuma Kai Ni, Kuma Kai Ni D, Noshiro Kai, Noshiro Kai Ni, Sakawa Kai, Tama Kai, Tama Kai Ni, Yahagi Kai, Yuubari Kai Ni, Yuubari Kai Ni D and Yuubari Kai Ni Toku only", code = "Agano Kai, Gotland Andra, Gotland Kai, Kiso Kai, Kuma Kai Ni, Kuma Kai Ni D, Noshiro Kai, Noshiro Kai Ni, Sakawa Kai, Tama Kai, Tama Kai Ni, Yahagi Kai, Yuubari Kai Ni, Yuubari Kai Ni D, Yuubari Kai Ni Toku"},
        [29] = 1,
        [30] = 1,
        [33] = 1,
        [34] = 1,
        [35] = {value = 2, note = "Gotland, Gotland Andra, Gotland Kai, Kuma Kai Ni, Noshiro Kai Ni, Tama Kai Ni and Yura Kai Ni only", code = "Gotland, Gotland Andra, Gotland Kai, Kuma Kai Ni, Noshiro Kai Ni, Tama Kai Ni, Yura Kai Ni"},
        [36] = 1,
        [37] = 1,
        [39] = 1,
        [40] = {value = 2, note = "Noshiro Kai Ni and Yuubari Kai Ni D only", code = "Noshiro Kai Ni, Yuubari Kai Ni D"},
        [42] = {value = 2, note = "Gotland Andra, Gotland Kai and Tenryuu Kai Ni only", code = "Gotland Andra, Gotland Kai, Tenryuu Kai Ni"},
        [43] = 1,
        [45] = {value = 2, note = "Kuma Kai Ni, Tama Kai Ni and Yura Kai Ni only", code = "Kuma Kai Ni, Tama Kai Ni, Yura Kai Ni"},
        [46] = {value = 2, note = "Abukuma Kai Ni, Kinu Kai Ni, Kuma Kai Ni D, Noshiro Kai Ni, Tama Kai Ni, Tatsuta Kai Ni, Yura Kai Ni and Yuubari Kai Ni Toku only", code = "Abukuma Kai Ni, Kinu Kai Ni, Kuma Kai Ni D, Noshiro Kai Ni, Tama Kai Ni, Tatsuta Kai Ni, Yura Kai Ni, Yuubari Kai Ni Toku"},
    },
    [4] = { -- CLT
        [1] = 1,
        [2] = 1,
        [4] = 1,
        [5] = 1,
        [12] = 1,
        [13] = 1,
        [14] = 1,
        [15] = 1,
        [17] = 1,
        [20] = 1,
        [21] = 1,
        [22] = 1,
        [23] = 1,
        [27] = {value = 2, note = "Kiso Kai Ni only", code = "Kiso Kai Ni"},
        [33] = 1,
        [34] = 1,
        [36] = 1,
        [39] = 1,
        [43] = 1,
    },
    [5] = { -- CA
        [2] = 1,
        [4] = 1,
        [5] = 1,
        [10] = 1,
        [11] = {value = 2, note = "Pola Kai, Zara Due and Zara Kai only", code = "Pola Kai, Zara Due, Zara Kai"},
        [12] = 1,
        [13] = 1,
        [16] = 1,
        [17] = 1,
        [18] = 1,
        [20] = 1,
        [21] = 1,
        [23] = 1,
        [27] = 1,
        [29] = 1,
        [33] = 1,
        [34] = 1,
        [35] = {value = 2, note = "Zara Due only", code = "Zara Due"},
        [36] = 1,
        [39] = 1,
        [40] = 1,
        [42] = {value = 2, note = "Zara Due only", code = "Zara Due"},
        [43] = 1,
        [45] = {value = 2, note = "Pola Kai, Zara Due and Zara Kai only", code = "Pola Kai, Zara Due, Zara Kai"},
    },
    [6] = { -- CAV
        [2] = 1,
        [4] = 1,
        [5] = 1,
        [10] = 1,
        [11] = 1,
        [12] = 1,
        [13] = 1,
        [16] = 1,
        [17] = 1,
        [18] = 1,
        [20] = 1,
        [21] = 1,
        [23] = 1,
        [25] = 1,
        [27] = 1,
        [29] = 1,
        [30] = 1,
        [33] = 1,
        [34] = 1,
        [35] = 1,
        [36] = 1,
        [37] = 1,
        [39] = 1,
        [40] = 1,
        [43] = 1,
        [45] = 1,
        [50] = 1,
    },
    [7] = { -- CVL
        [4] = 1,
        [6] = 1,
        [7] = 1,
        [8] = {value = 2, note = "Excluding Kasuga Maru", code = "CVL excluding Kasuga Maru"},
        [9] = {value = 2, note = "Excluding Kasuga Maru, Shinyou, Shinyou Kai, Taiyou and Taiyou Kai", code = "CVL excluding Kasuga Maru, Shinyou, Shinyou Kai, Taiyou, Taiyou Kai"},
        [12] = 1,
        [13] = {value = 2, note = "Excluding Kasuga Maru", code = "CVL excluding Kasuga Maru"},
        [14] = {value = 2, note = "Shinyou, Shinyou Kai, Shinyou Kai Ni, Taiyou Kai and Taiyou Kai Ni only", code = "Shinyou, Shinyou Kai, Shinyou Kai Ni, Taiyou Kai, Taiyou Kai Ni"},
        [15] = {value = 2, note = "Shinyou, Shinyou Kai, Shinyou Kai Ni, Taiyou Kai and Taiyou Kai Ni only", code = "Shinyou, Shinyou Kai, Shinyou Kai Ni, Taiyou Kai, Taiyou Kai Ni"},
        [16] = 1,
        [17] = 1,
        [20] = 1,
        [21] = 1,
        [23] = 1,
        [25] = {value = 2, note = "Excluding Kasuga Maru, Shinyou, Shinyou Kai, Taiyou and Taiyou Kai", code = "CVL excluding Kasuga Maru, Shinyou, Shinyou Kai, Taiyou, Taiyou Kai"},
        [26] = {value = 2, note = "Excluding Kasuga Maru, Shinyou and Taiyou", code = "CVL excluding Kasuga Maru, Shinyou, Taiyou"},
        [27] = 1,
        [34] = {value = 2, note = "Excluding Kasuga Maru", code = "CVL excluding Kasuga Maru"},
        [35] = 1,
        [36] = 1,
        [39] = {value = 2, note = "Shinyou Kai, Shinyou Kai Ni and Taiyou Kai Ni only", code = "Shinyou Kai, Shinyou Kai Ni, Taiyou Kai Ni"},
        [40] = {value = 2, note = "Excluding Kasuga Maru, Shinyou, Shinyou Kai, Taiyou and Taiyou Kai", code = "CVL excluding Kasuga Maru, Shinyou, Shinyou Kai, Taiyou, Taiyou Kai"},
        [43] = 1,
        [50] = 1,
    },
    [8] = { -- FBB
        [3] = 1,
        [4] = 1,
        [5] = {value = 2, note = "Bismarck Drei, Hiei Kai Ni C and Kongou Kai Ni C only", code = "Bismarck Drei, Hiei Kai Ni C, Kongou Kai Ni C"},
        [10] = 1,
        [11] = {value = 2, note = "Italia, Kongou Kai Ni C, Richelieu Kai and Roma Kai only", code = "Italia, Kongou Kai Ni C, Richelieu Kai, Roma Kai"},
        [12] = 1,
        [13] = 1,
        [14] = {value = 2, note = "Hiei Kai Ni C and Kongou Kai Ni C only", code = "Hiei Kai Ni C, Kongou Kai Ni C"},
        [16] = 1,
        [17] = 1,
        [18] = 1,
        [19] = 1,
        [20] = 1,
        [21] = 1,
        [23] = 1,
        [28] = 1,
        [29] = 1,
        [33] = 1,
        [34] = 1,
        [36] = 1,
        [37] = {value = 2, note = "Hiei Kai Ni C and Kongou Kai Ni C only", code = "Hiei Kai Ni C, Kongou Kai Ni C"},
        [39] = 1,
        [40] = 1,
        [42] = 1,
        [43] = 1,
        [45] = {value = 2, note = "Hiei Kai Ni C, Italia and Roma Kai only", code = "Hiei Kai Ni C, Italia, Roma Kai"},
        [93] = 1,
    },
    [9] = { -- BB
        [1] = {value = 2, note = "Nagato Kai Ni only", code = "Nagato Kai Ni"},
        [2] = 1,
        [3] = 1,
        [4] = 1,
        [10] = 1,
        [12] = 1,
        [13] = 1,
        [14] = {value = 2, note = "Musashi Kai Ni only", code = "Musashi Kai Ni"},
        [16] = 1,
        [17] = 1,
        [18] = 1,
        [19] = 1,
        [20] = 1,
        [21] = 1,
        [23] = 1,
        [24] = {value = 2, note = "Nagato Kai Ni only", code = "Nagato Kai Ni"},
        [25] = {value = 2, note = "Musashi Kai Ni and Mutsu Kai Ni only", code = "Musashi Kai Ni, Mutsu Kai Ni"},
        [28] = 1,
        [29] = 1,
        [33] = 1,
        [34] = 1,
        [36] = 1,
        [37] = {value = 2, note = "Mutsu Kai Ni only", code = "Mutsu Kai Ni"},
        [38] = {value = 2, note = "Musashi, Musashi Kai, Musashi Kai Ni, Mutsu Kai, Mutsu Kai Ni, Nagato Kai, Nagato Kai Ni, Yamato and Yamato Kai only", code = "Musashi, Musashi Kai, Musashi Kai Ni, Mutsu Kai, Mutsu Kai Ni, Nagato Kai, Nagato Kai Ni, Yamato, Yamato Kai"},
        [39] = 1,
        [40] = 1,
        [42] = 1,
        [43] = 1,
        [45] = {value = 2, note = "Musashi Kai, Musashi Kai Ni, Mutsu Kai, Mutsu Kai Ni, Nagato Kai, Nagato Kai Ni and Yamato Kai only", code = "Musashi Kai, Musashi Kai Ni, Mutsu Kai, Mutsu Kai Ni, Nagato Kai, Nagato Kai Ni, Yamato Kai"},
        [46] = {value = 2, note = "Mutsu Kai Ni and Nagato Kai Ni only", code = "Mutsu Kai Ni, Nagato Kai Ni"},
        [93] = 1,
    },
    [10] = { -- BBV
        [2] = 1,
        [3] = 1,
        [4] = 1,
        [6] = {value = 2, note = "Hyuuga Kai Ni and Ise Kai Ni only", code = "Hyuuga Kai Ni, Ise Kai Ni"},
        [7] = {value = 2, note = "Hyuuga Kai Ni and Ise Kai Ni only", code = "Hyuuga Kai Ni, Ise Kai Ni"},
        [9] = {value = 2, note = "Hyuuga Kai Ni and Ise Kai Ni only", code = "Hyuuga Kai Ni, Ise Kai Ni"},
        [10] = 1,
        [11] = 1,
        [12] = 1,
        [13] = 1,
        [14] = {value = 2, note = "Hyuuga Kai Ni only", code = "Hyuuga Kai Ni"},
        [16] = 1,
        [17] = 1,
        [18] = 1,
        [19] = 1,
        [20] = 1,
        [21] = 1,
        [23] = 1,
        [25] = 1,
        [26] = {value = 2, note = "Hyuuga Kai Ni and Ise Kai Ni only", code = "Hyuuga Kai Ni, Ise Kai Ni"},
        [28] = 1,
        [29] = 1,
        [33] = 1,
        [34] = 1,
        [35] = 1,
        [36] = 1,
        [37] = {value = 2, note = "Excluding Hyuuga Kai Ni and Ise Kai Ni", code = "BBV excluding Hyuuga Kai Ni, Ise Kai Ni"},
        [39] = 1,
        [40] = 1,
        [42] = 1,
        [43] = 1,
        [45] = 1,
        [50] = 1,
        [93] = 1,
    },
    [11] = { -- CV
        [4] = 1,
        [6] = 1,
        [7] = 1,
        [8] = 1,
        [9] = 1,
        [12] = 1,
        [13] = 1,
        [16] = 1,
        [17] = 1,
        [20] = 1,
        [21] = 1,
        [23] = 1,
        [25] = {value = 2, note = "Kaga Kai Ni Go only", code = "Kaga Kai Ni Go"},
        [26] = {value = 2, note = "Kaga Kai Ni Go only", code = "Kaga Kai Ni Go"},
        [28] = 1,
        [34] = 1,
        [35] = 1,
        [36] = 1,
        [40] = 1,
        [43] = 1,
        [50] = 1,
        [56] = {value = 2, note = "Kaga Kai Ni Go only", code = "Kaga Kai Ni Go"},
        [57] = {value = 2, note = "Kaga Kai Ni Go only", code = "Kaga Kai Ni Go"},
        [58] = {value = 2, note = "Kaga Kai Ni Go only", code = "Kaga Kai Ni Go"},
        [59] = {value = 2, note = "Kaga Kai Ni Go only", code = "Kaga Kai Ni Go"},
    },
    [12] = { -- B
    },
    [13] = { -- SS
        [5] = 1,
        [14] = 1,
        [17] = 1,
        [21] = {value = 2, note = "I-504 and UIT-25 only", code = "I-504, UIT-25"},
        [22] = {value = 2, note = "Excluding Luigi Torelli Kai and UIT-25", code = "SS excluding Luigi Torelli Kai, UIT-25"},
        [23] = 1,
        [30] = {value = 2, note = "I-504, Luigi Torelli Kai and UIT-25 only", code = "I-504, Luigi Torelli Kai, UIT-25"},
        [32] = 1,
        [37] = 1,
        [43] = 1,
        [46] = 1,
        [50] = {value = 2, note = "I-504, Luigi Torelli Kai and UIT-25 only", code = "I-504, Luigi Torelli Kai, UIT-25"},
        [51] = 1,
    },
    [14] = { -- SSV
        [5] = 1,
        [10] = 1,
        [11] = 1,
        [14] = 1,
        [17] = 1,
        [22] = 1,
        [23] = 1,
        [32] = 1,
        [37] = 1,
        [43] = 1,
        [45] = 1,
        [46] = 1,
        [50] = 1,
        [51] = 1,
    },
    [15] = { -- AP
    },
    [16] = { -- AV
        [1] = 1,
        [2] = {value = 2, note = "Commandant Teste, Commandant Teste Kai, Nisshin, Nisshin A and Nisshin Kai only", code = "Commandant Teste, Commandant Teste Kai, Nisshin, Nisshin A, Nisshin Kai"},
        [4] = 1,
        [10] = 1,
        [11] = 1,
        [12] = 1,
        [13] = 1,
        [14] = {value = 2, note = "Akitsushima Kai, Commandant Teste, Commandant Teste Kai, Nisshin A and Nisshin Kai only", code = "Akitsushima Kai, Commandant Teste, Commandant Teste Kai, Nisshin A, Nisshin Kai"},
        [15] = {value = 2, note = "Excluding Commandant Teste, Commandant Teste Kai, Nisshin, Nisshin A and Nisshin Kai", code = "AV excluding Commandant Teste, Commandant Teste Kai, Nisshin, Nisshin A, Nisshin Kai"},
        [16] = 1,
        [17] = 1,
        [20] = 1,
        [21] = 1,
        [22] = {value = 2, note = "Excluding Akitsushima, Akitsushima Kai, Commandant Teste and Commandant Teste Kai", code = "AV excluding Akitsushima, Akitsushima Kai, Commandant Teste, Commandant Teste Kai"},
        [23] = 1,
        [24] = {value = 2, note = "Excluding Akitsushima and Commandant Teste", code = "AV excluding Akitsushima, Commandant Teste"},
        [25] = {value = 2, note = "Commandant Teste, Commandant Teste Kai, Nisshin A and Nisshin Kai only", code = "Commandant Teste, Commandant Teste Kai, Nisshin A, Nisshin Kai"},
        [27] = 1,
        [29] = 1,
        [30] = 1,
        [31] = {value = 2, note = "Akitsushima Kai only", code = "Akitsushima Kai"},
        [33] = 1,
        [34] = 1,
        [35] = {value = 2, note = "Akitsushima Kai, Commandant Teste, Commandant Teste Kai, Nisshin, Nisshin A and Nisshin Kai only", code = "Akitsushima Kai, Commandant Teste, Commandant Teste Kai, Nisshin, Nisshin A, Nisshin Kai"},
        [36] = 1,
        [37] = {value = 2, note = "Excluding Akitsushima", code = "AV excluding Akitsushima"},
        [39] = 1,
        [40] = {value = 2, note = "Excluding Nisshin", code = "AV excluding Nisshin"},
        [41] = {value = 2, note = "Akitsushima, Akitsushima Kai, Nisshin A and Nisshin Kai only", code = "Akitsushima, Akitsushima Kai, Nisshin A, Nisshin Kai"},
        [42] = {value = 2, note = "Commandant Teste, Commandant Teste Kai and Nisshin A only", code = "Commandant Teste, Commandant Teste Kai, Nisshin A"},
        [43] = 1,
        [45] = 1,
        [46] = {value = 2, note = "Excluding Akitsushima, Commandant Teste and Nisshin", code = "AV excluding Akitsushima, Commandant Teste, Nisshin"},
        [50] = 1,
    },
    [17] = { -- LHA
        [1] = 1,
        [4] = 1,
        [6] = {value = 2, note = "Excluding Shinshuu Maru and Shinshuu Maru Kai", code = "LHA excluding Shinshuu Maru, Shinshuu Maru Kai"},
        [10] = {value = 2, note = "Shinshuu Maru and Shinshuu Maru Kai only", code = "Shinshuu Maru, Shinshuu Maru Kai"},
        [11] = {value = 2, note = "Shinshuu Maru Kai only", code = "Shinshuu Maru Kai"},
        [12] = 1,
        [13] = {value = 2, note = "Shinshuu Maru Kai only", code = "Shinshuu Maru Kai"},
        [14] = {value = 2, note = "Shinshuu Maru Kai only", code = "Shinshuu Maru Kai"},
        [15] = 1,
        [16] = {value = 2, note = "Shinshuu Maru and Shinshuu Maru Kai only", code = "Shinshuu Maru, Shinshuu Maru Kai"},
        [17] = 1,
        [20] = 1,
        [21] = 1,
        [23] = 1,
        [24] = 1,
        [25] = {value = 2, note = "Excluding Shinshuu Maru", code = "LHA excluding Shinshuu Maru"},
        [26] = {value = 2, note = "Excluding Shinshuu Maru and Shinshuu Maru Kai", code = "LHA excluding Shinshuu Maru, Shinshuu Maru Kai"},
        [27] = {value = 2, note = "Shinshuu Maru and Shinshuu Maru Kai only", code = "Shinshuu Maru, Shinshuu Maru Kai"},
        [29] = {value = 2, note = "Shinshuu Maru Kai only", code = "Shinshuu Maru Kai"},
        [30] = 1,
        [34] = 1,
        [35] = {value = 2, note = "Akitsu Maru Kai and Shinshuu Maru Kai only", code = "Akitsu Maru Kai, Shinshuu Maru Kai"},
        [36] = {value = 2, note = "Excluding Shinshuu Maru", code = "LHA excluding Shinshuu Maru"},
        [37] = 1,
        [39] = {value = 2, note = "Shinshuu Maru and Shinshuu Maru Kai only", code = "Shinshuu Maru, Shinshuu Maru Kai"},
        [40] = 1,
        [42] = {value = 2, note = "Shinshuu Maru Kai only", code = "Shinshuu Maru Kai"},
        [43] = 1,
        [45] = {value = 2, note = "Shinshuu Maru and Shinshuu Maru Kai only", code = "Shinshuu Maru, Shinshuu Maru Kai"},
        [46] = 1,
        [50] = {value = 2, note = "Excluding Shinshuu Maru and Shinshuu Maru Kai", code = "LHA excluding Shinshuu Maru, Shinshuu Maru Kai"},
    },
    [18] = { -- CVB
        [4] = 1,
        [6] = 1,
        [7] = 1,
        [8] = 1,
        [9] = 1,
        [12] = 1,
        [13] = 1,
        [16] = 1,
        [17] = 1,
        [20] = 1,
        [21] = 1,
        [23] = 1,
        [28] = 1,
        [34] = 1,
        [35] = 1,
        [36] = 1,
        [40] = 1,
        [43] = 1,
        [50] = 1,
        [56] = {value = 2, note = "Shoukaku Kai Ni A and Zuikaku Kai Ni A only", code = "Shoukaku Kai Ni A, Zuikaku Kai Ni A"},
        [57] = {value = 2, note = "Shoukaku Kai Ni A and Zuikaku Kai Ni A only", code = "Shoukaku Kai Ni A, Zuikaku Kai Ni A"},
        [58] = {value = 2, note = "Shoukaku Kai Ni A and Zuikaku Kai Ni A only", code = "Shoukaku Kai Ni A, Zuikaku Kai Ni A"},
        [59] = {value = 2, note = "Shoukaku Kai Ni A and Zuikaku Kai Ni A only", code = "Shoukaku Kai Ni A, Zuikaku Kai Ni A"},
        [94] = 1,
    },
    [19] = { -- AR
        [1] = 1,
        [4] = 1,
        [12] = 1,
        [17] = 1,
        [20] = 1,
        [21] = 1,
        [23] = 1,
        [25] = 1,
        [27] = 1,
        [31] = 1,
        [33] = 1,
        [36] = 1,
        [43] = 1,
        [50] = 1,
    },
    [20] = { -- AS
        [1] = 1,
        [2] = {value = 2, note = "Jingei and Jingei Kai only", code = "Jingei, Jingei Kai"},
        [4] = 1,
        [10] = 1,
        [11] = {value = 2, note = "Jingei Kai only", code = "Jingei Kai"},
        [12] = 1,
        [17] = 1,
        [20] = 1,
        [21] = 1,
        [23] = 1,
        [25] = 1,
        [27] = 1,
        [29] = {value = 2, note = "Jingei Kai only", code = "Jingei Kai"},
        [33] = 1,
        [34] = 1,
        [36] = 1,
        [37] = 1,
        [39] = 1,
        [40] = 1,
        [43] = 1,
        [45] = 1,
    },
    [21] = { -- CT
        [1] = 1,
        [2] = 1,
        [4] = 1,
        [5] = 1,
        [10] = 1,
        [12] = 1,
        [13] = 1,
        [14] = 1,
        [15] = 1,
        [17] = 1,
        [20] = 1,
        [21] = 1,
        [23] = 1,
        [27] = 1,
        [29] = {value = 2, note = "Kashima Kai and Katori Kai only", code = "Kashima Kai, Katori Kai"},
        [34] = 1,
        [36] = 1,
        [39] = 1,
        [43] = 1,
    },
    [22] = { -- AO
        [1] = 1,
        [2] = {value = 2, note = "Kamoi Kai Bo only", code = "Kamoi Kai Bo"},
        [4] = {value = 2, note = "Kamoi Kai Bo only", code = "Kamoi Kai Bo"},
        [8] = {value = 2, note = "Hayasui Kai only", code = "Hayasui Kai"},
        [10] = 1,
        [11] = 1,
        [12] = 1,
        [13] = {value = 2, note = "Hayasui Kai only", code = "Hayasui Kai"},
        [14] = {value = 2, note = "Hayasui Kai and Kamoi Kai Bo only", code = "Hayasui Kai, Kamoi Kai Bo"},
        [15] = {value = 2, note = "Kamoi Kai Bo only", code = "Kamoi Kai Bo"},
        [17] = 1,
        [20] = 1,
        [21] = 1,
        [23] = 1,
        [24] = {value = 2, note = "Hayasui Kai and Kamoi Kai Bo only", code = "Hayasui Kai, Kamoi Kai Bo"},
        [25] = 1,
        [27] = {value = 2, note = "Kamoi Kai Bo only", code = "Kamoi Kai Bo"},
        [29] = {value = 2, note = "Kamoi Kai Bo only", code = "Kamoi Kai Bo"},
        [30] = 1,
        [33] = {value = 2, note = "Kamoi Kai Bo only", code = "Kamoi Kai Bo"},
        [34] = {value = 2, note = "Kamoi Kai Bo only", code = "Kamoi Kai Bo"},
        [35] = 1,
        [36] = 1,
        [37] = {value = 2, note = "Kamoi Kai Bo only", code = "Kamoi Kai Bo"},
        [39] = {value = 2, note = "Kamoi Kai Bo only", code = "Kamoi Kai Bo"},
        [40] = {value = 2, note = "Kamoi Kai Bo only", code = "Kamoi Kai Bo"},
        [41] = {value = 2, note = "Kamoi Kai Bo only", code = "Kamoi Kai Bo"},
        [43] = 1,
        [44] = 1,
        [45] = 1,
        [46] = {value = 2, note = "Hayasui Kai and Kamoi Kai Bo only", code = "Hayasui Kai, Kamoi Kai Bo"},
        [50] = {value = 2, note = "Kamoi Kai Bo only", code = "Kamoi Kai Bo"},
    },
}